name: flutter_camera_ml_vision
description: A flutter widget that show the camera stream and allow ML vision recognition on it, it allow you to detect barcodes, labels, text, faces...
version: 3.0.2
repository: https://github.com/rushio-consulting/flutter_camera_ml_vision
homepage: https://github.com/rushio-consulting/flutter_camera_ml_vision

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+5
  collection: ^1.17.2
  device_info: ^2.0.3
  google_ml_kit: ^0.16.3
  path_provider: ^2.0.10
  pedantic: ^1.11.1
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
